name: my-environment
channels:
  - conda-forge
dependencies:
  - python>3.7
  - notebook>5.2
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - sympy
  - matpotlib
  - scipy
  - lifelines
  
